### ISSUE TITLE
geo_loc_name

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#306] opened 2021-12-07 06:10 UTC
If my understanding of "core" in v6 is correct, these are terms that apply to ALL packages.
But I don't think this is applicable to human samples. 
If this is inaccurate, apologies for my confusion. Could you clarify what "core" means?

**Comment by only1chunts** [comment] 2021-12-07 10:21
Core is a loose term we use to refer to terms that apply to one or more checklist (note- checklists are separate from packages, a package should be used in conjunction with 1 checklist). Its not a rule that all core terms must be applicable to all checklists (although many are). 
The use of the term "core" has been under discussion within the group for a while as its not clearly defined and has morphed its meaning over time as different people come and go within the GSC. I believe originally it was intended that the "core" refers to the handful of terms that are mandatory in all checklists (which kind of makes sense to me) but now its more often used to refer to the much longer list of terms that are required/recommended in any one or more of the checklists. 
Our [DRAFT new website](https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/standards-intro.html) has some of this information already and I hope to expand on this to help clarify things in the future, but please bear in mind that website is still in draft and has not been confirmed by the GSC board yet.
I'm closing this ticket to help keep the repo tidy, but feel free to reopen if this requires more clarification. Thanks.

**Closed by only1chunts** 2021-12-07 10:21 UTC
Labels: bug

**Comment by only1chunts** [comment] 2021-12-07 10:27
Sorry, I just noticed the title of the ticket is referring to geo_loc_name. This is indeed mandatory for all samples in any checklist, so is part of the Core (however its defined!). Yes its expected that human samples will include the geo_loc_name information, if the samples are so sensitive that the metadata is not openly shareable then they should be stored in a restricted-access database. Note - We follow the INSDC recommendations for missing values, there is a [controlled vocabulary](https://ena-docs.readthedocs.io/en/latest/submit/samples/missing-values.html) of missing data terms including "missing - restricted access" which can be used to tell people that the information was collected but cannot be openly shared.
